Fixed if-statement
temando/serverless-openapi-documentation pull request #24
Opened 2018-07-11 08:14 UTC by David-Sellen

Hi! Fixed if-statement related to #16 since it caused parameters and request bodies to be ignored.

2018-08-02 15:11 UTC, jhaagmans requested changes

2018-08-02 15:11 UTC, jhaagmans commented on src/DefinitionGenerator.ts
> +    if (documentationConfig.parameters) {
This should be `documentationConfig.queryParams`, as parameters in Swagger are names `queryParams` in this plugin.

2018-08-02 15:14 UTC, jhaagmans commented on src/DefinitionGenerator.ts
> +    if (documentationConfig.parameters) {
Hmm, thinking about this, you might have to check for the existence of _any_ type of parameter, be it path, query, header (undocumented) or cookie.

2018-08-09 22:49 UTC, kzhou57 commented
Tested it, it doesn't sound working. PR #27 doesn't work either

2018-08-30 11:42 UTC, closed without merging

2018-08-30 11:43 UTC, nfour commented
See [#27](https://github.com/temando/serverless-openapi-documentation/pull/27#issuecomment-417289664)